Feature/issue2637
AtlasOfLivingAustralia/fieldcapture pull request #2795
Opened 2023-01-30 03:12 UTC by salomon-j

2023-02-27 21:44 UTC, chrisala requested changes
This implementation will allow unsubmitted reports with data to be completely deleted by an end date change.

If the last report with data is not approved, the date should be allowed to be changed such that it's > the report start date.
If the last report with data is submitted/approved, the date must be >= the report end date.

2023-03-02 23:50 UTC, salomon-j commented
I overlooked to test that scenario, mostly tested wherein the new end date is always after the report start date.
I'm currently debugging to find the method or part of code that will not delete the unsubmitted report with data  if the change end date is before the report start date.

2023-04-03 04:01 UTC, chrisala requested changes

2023-04-03 04:01 UTC, chrisala commented on grails-app/services/au/org/ala/merit/ProjectService.groovy
> +    boolean excludesNotApproved(Map report) {
Is this used?  It also looks like a duplicate of the method in the ReportService

2023-04-03 04:01 UTC, chrisala commented on grails-app/services/au/org/ala/merit/ProjectService.groovy
> +            if (lastReport && plannedEndDateAlignedToReportingSchedule < lastReport.fromDate) {
This allows the report to be completely deleted.
It should also take into account the minimum report length setting in the project config.

2023-06-21 01:53 UTC, merged